// src/lib/words.ts
export type WordPair = { secret: string; hint: string; theme: string };

export const DEFAULT_WORDS: WordPair[] = [
  // Food
  { secret: 'Pizza', hint: 'Cheese', theme: 'food' },
  { secret: 'Burger', hint: 'Bun', theme: 'food' },
  { secret: 'Sushi', hint: 'Rice', theme: 'food' },
  { secret: 'Pasta', hint: 'Italy', theme: 'food' },
  { secret: 'Chocolate', hint: 'Cocoa', theme: 'food' },
  { secret: 'Apple', hint: 'Red', theme: 'food' },
  { secret: 'Coffee', hint: 'Bean', theme: 'food' },
  { secret: 'Bread', hint: 'Yeast', theme: 'food' },
  { secret: 'Ice Cream', hint: 'Cold', theme: 'food' },
  { secret: 'Salad', hint: 'Lettuce', theme: 'food' },
  { secret: 'Taco', hint: 'Shell', theme: 'food' },
  { secret: 'Steak', hint: 'Grill', theme: 'food' },
  { secret: 'Soup', hint: 'Bowl', theme: 'food' },
  { secret: 'Sandwich', hint: 'Bread', theme: 'food' },
  { secret: 'Pancake', hint: 'Syrup', theme: 'food' },
  { secret: 'Waffle', hint: 'Grid', theme: 'food' },
  { secret: 'Omelette', hint: 'Eggs', theme: 'food' },
  { secret: 'Bacon', hint: 'Crispy', theme: 'food' },
  { secret: 'Hot Dog', hint: 'Sausage', theme: 'food' },
  { secret: 'French Fries', hint: 'Potato', theme: 'food' },
  { secret: 'Onion Rings', hint: 'Fried', theme: 'food' },
  { secret: 'Fried Chicken', hint: 'Crunchy', theme: 'food' },
  { secret: 'Sausage', hint: 'Links', theme: 'food' },
  { secret: 'Meatball', hint: 'Spaghetti', theme: 'food' },
  { secret: 'Lasagna', hint: 'Layers', theme: 'food' },
  { secret: 'Ravioli', hint: 'Filled', theme: 'food' },
  { secret: 'Ramen', hint: 'Noodles', theme: 'food' },
  { secret: 'Curry', hint: 'Spicy', theme: 'food' },
  { secret: 'Stir Fry', hint: 'Wok', theme: 'food' },
  { secret: 'Dumplings', hint: 'Steamed', theme: 'food' },
  { secret: 'Spring Rolls', hint: 'Crunchy', theme: 'food' },
  { secret: 'Sashimi', hint: 'Raw', theme: 'food' },
  { secret: 'Tempura', hint: 'Battered', theme: 'food' },
  { secret: 'Paella', hint: 'Spanish', theme: 'food' },
  { secret: 'Tagine', hint: 'Moroccan', theme: 'food' },
  { secret: 'Gyro', hint: 'Greek', theme: 'food' },
  { secret: 'Kebab', hint: 'Skewer', theme: 'food' },
  { secret: 'Falafel', hint: 'Chickpeas', theme: 'food' },
  { secret: 'Hummus', hint: 'Dip', theme: 'food' },
  { secret: 'Guacamole', hint: 'Avocado', theme: 'food' },
  { secret: 'Salsa', hint: 'Tomato', theme: 'food' },
  { secret: 'Quesadilla', hint: 'Cheese', theme: 'food' },
  { secret: 'Burrito', hint: 'Wrapped', theme: 'food' },
  { secret: 'Enchilada', hint: 'Sauce', theme: 'food' },
  { secret: 'Nachos', hint: 'Chips', theme: 'food' },
  { secret: 'Chili', hint: 'Beans', theme: 'food' },
  { secret: 'Gumbo', hint: 'Louisiana', theme: 'food' },
  { secret: 'Jambalaya', hint: 'Rice', theme: 'food' },
  { secret: 'Clam Chowder', hint: 'Creamy', theme: 'food' },
  { secret: 'Lobster', hint: 'Shellfish', theme: 'food' },
  { secret: 'Crab', hint: 'Pincers', theme: 'food' },
  { secret: 'Shrimp', hint: 'Prawn', theme: 'food' },
  { secret: 'Salmon', hint: 'Pink', theme: 'food' },
  { secret: 'Tuna', hint: 'Canned', theme: 'food' },
  { secret: 'Sardines', hint: 'Small', theme: 'food' },
  { secret: 'Caviar', hint: 'Eggs', theme: 'food' },
  { secret: 'Foie Gras', hint: 'Duck', theme: 'food' },
  { secret: 'Escargot', hint: 'Snails', theme: 'food' },
  { secret: 'Risotto', hint: 'Creamy', theme: 'food' },
  { secret: 'Polenta', hint: 'Corn', theme: 'food' },
  { secret: 'Quiche', hint: 'Pie', theme: 'food' },
  { secret: 'Frittata', hint: 'Italian', theme: 'food' },
  { secret: 'Croissant', hint: 'Flaky', theme: 'food' },
  { secret: 'Bagel', hint: 'Hole', theme: 'food' },
  { secret: 'Muffin', hint: 'Blueberry', theme: 'food' },
  { secret: 'Donut', hint: 'Hole', theme: 'food' },
  { secret: 'Cupcake', hint: 'Frosting', theme: 'food' },
  { secret: 'Cheesecake', hint: 'Creamy', theme: 'food' },
  { secret: 'Brownie', hint: 'Chocolate', theme: 'food' },
  { secret: 'Cookie', hint: 'Chips', theme: 'food' },
  { secret: 'Pie', hint: 'Crust', theme: 'food' },
  { secret: 'Cake', hint: 'Birthday', theme: 'food' },
  { secret: 'Pudding', hint: 'Dessert', theme: 'food' },
  { secret: 'Jello', hint: 'Wobbly', theme: 'food' },
  { secret: 'Yogurt', hint: 'Probiotic', theme: 'food' },
  { secret: 'Cheese', hint: 'Dairy', theme: 'food' },
  { secret: 'Butter', hint: 'Spread', theme: 'food' },
  { secret: 'Milk', hint: 'Cow', theme: 'food' },
  { secret: 'Egg', hint: 'Shell', theme: 'food' },
  { secret: 'Honey', hint: 'Bee', theme: 'food' },
  { secret: 'Jam', hint: 'Fruit', theme: 'food' },
  { secret: 'Peanut Butter', hint: 'Spread', theme: 'food' },
  { secret: 'Cereal', hint: 'Breakfast', theme: 'food' },
  { secret: 'Oatmeal', hint: 'Porridge', theme: 'food' },
  { secret: 'Granola', hint: 'Crunchy', theme: 'food' },
  { secret: 'Trail Mix', hint: 'Nuts', theme: 'food' },
  { secret: 'Popcorn', hint: 'Movie', theme: 'food' },
  { secret: 'Chips', hint: 'Crispy', theme: 'food' },
  { secret: 'Pretzel', hint: 'Twisted', theme: 'food' },
  { secret: 'Cracker', hint: 'Salty', theme: 'food' },
  { secret: 'Nuts', hint: 'Almonds', theme: 'food' },
  { secret: 'Seeds', hint: 'Sunflower', theme: 'food' },
  { secret: 'Dried Fruit', hint: 'Raisins', theme: 'food' },
  { secret: 'Pickles', hint: 'Brined', theme: 'food' },
  { secret: 'Olives', hint: 'Mediterranean', theme: 'food' },
  { secret: 'Herbs', hint: 'Basil', theme: 'food' },
  { secret: 'Spices', hint: 'Pepper', theme: 'food' },
  { secret: 'Salt', hint: 'Sodium', theme: 'food' },
  { secret: 'Pepper', hint: 'Black', theme: 'food' },
  { secret: 'Oil', hint: 'Olive', theme: 'food' },
  { secret: 'Vinegar', hint: 'Sour', theme: 'food' },
  { secret: 'Soy Sauce', hint: 'Asian', theme: 'food' },
  { secret: 'Ketchup', hint: 'Tomato', theme: 'food' },
  { secret: 'Mustard', hint: 'Yellow', theme: 'food' },
  { secret: 'Mayonnaise', hint: 'Creamy', theme: 'food' },
  { secret: 'Relish', hint: 'Pickle', theme: 'food' },
  { secret: 'Soda', hint: 'Fizzy', theme: 'food' },
  { secret: 'Juice', hint: 'Orange', theme: 'food' },
  { secret: 'Smoothie', hint: 'Blended', theme: 'food' },
  { secret: 'Milkshake', hint: 'Ice Cream', theme: 'food' },
  { secret: 'Tea', hint: 'Leaves', theme: 'food' },
  { secret: 'Wine', hint: 'Grapes', theme: 'food' },
  { secret: 'Beer', hint: 'Hops', theme: 'food' },
  { secret: 'Cocktail', hint: 'Mixed', theme: 'food' },

  // Jobs
  { secret: 'Doctor', hint: 'Hospital', theme: 'jobs' },
  { secret: 'Teacher', hint: 'Classroom', theme: 'jobs' },
  { secret: 'Chef', hint: 'Kitchen', theme: 'jobs' },
  { secret: 'Pilot', hint: 'Airplane', theme: 'jobs' },
  { secret: 'Police', hint: 'Badge', theme: 'jobs' },
  { secret: 'Firefighter', hint: 'Rescue', theme: 'jobs' },
  { secret: 'Artist', hint: 'Paint', theme: 'jobs' },
  { secret: 'Engineer', hint: 'Build', theme: 'jobs' },
  { secret: 'Farmer', hint: 'Field', theme: 'jobs' },
  { secret: 'Musician', hint: 'Instrument', theme: 'jobs' },
  { secret: 'Nurse', hint: 'Patient', theme: 'jobs' },
  { secret: 'Lawyer', hint: 'Court', theme: 'jobs' },
  { secret: 'Judge', hint: 'Gavel', theme: 'jobs' },
  { secret: 'Electrician', hint: 'Wires', theme: 'jobs' },
  { secret: 'Plumber', hint: 'Pipe', theme: 'jobs' },
  { secret: 'Mechanic', hint: 'Garage', theme: 'jobs' },
  { secret: 'Journalist', hint: 'Report', theme: 'jobs' },
  { secret: 'Scientist', hint: 'Lab', theme: 'jobs' },
  { secret: 'Actor', hint: 'Stage', theme: 'jobs' },
  { secret: 'Dancer', hint: 'Performance', theme: 'jobs' },
  { secret: 'Author', hint: 'Book', theme: 'jobs' },
  { secret: 'Photographer', hint: 'Camera', theme: 'jobs' },
  { secret: 'Designer', hint: 'Sketch', theme: 'jobs' },
  { secret: 'Coach', hint: 'Team', theme: 'jobs' },
  { secret: 'Dentist', hint: 'Teeth', theme: 'jobs' },
  { secret: 'Architect', hint: 'Blueprint', theme: 'jobs' },
  

  // Places
  { secret: 'Bank', hint: 'Money', theme: 'places' },
  { secret: 'Airport', hint: 'Flight', theme: 'places' },
  { secret: 'School', hint: 'Students', theme: 'places' },
  { secret: 'Library', hint: 'Books', theme: 'places' },
  { secret: 'Museum', hint: 'Art', theme: 'places' },
  { secret: 'Park', hint: 'Trees', theme: 'places' },
  { secret: 'Beach', hint: 'Sand', theme: 'places' },
  { secret: 'Hospital', hint: 'Care', theme: 'places' },
  { secret: 'Restaurant', hint: 'Menu', theme: 'places' },
  { secret: 'Cinema', hint: 'Movies', theme: 'places' },
  { secret: 'Train Station', hint: 'Platform', theme: 'places' },
  { secret: 'Airport Lounge', hint: 'Waiting', theme: 'places' },
  { secret: 'Supermarket', hint: 'Groceries', theme: 'places' },
  { secret: 'Hotel', hint: 'Room', theme: 'places' },
  { secret: 'Zoo', hint: 'Animals', theme: 'places' },
  { secret: 'Stadium', hint: 'Crowd', theme: 'places' },
  { secret: 'Cafe', hint: 'Coffee', theme: 'places' },
  { secret: 'Theater', hint: 'Stage', theme: 'places' },
  { secret: 'Beach Resort', hint: 'Vacation', theme: 'places' },
  { secret: 'Church', hint: 'Worship', theme: 'places' },
  { secret: 'Market', hint: 'Shops', theme: 'places' },
  { secret: 'Bridge', hint: 'River', theme: 'places' },
  { secret: 'Mountain', hint: 'Climb', theme: 'places' },
  { secret: 'Harbor', hint: 'Ships', theme: 'places' },
  { secret: 'Garden', hint: 'Flowers', theme: 'places' },
  { secret: 'Factory', hint: 'Machines', theme: 'places' },
  { secret: 'Bus Stop', hint: 'Waiting', theme: 'places' },
  { secret: 'Airport Terminal', hint: 'Flight', theme: 'places' },
  { secret: 'Mosque', hint: 'Prayer', theme: 'places' },
  { secret: 'S', hint: 'Worship', theme: 'places' },
  { secret: 'Synagogue', hint: 'Torah', theme: 'places' },
  { secret: 'Gurdwara', hint: 'Prayer', theme: 'places' },


  // Objects
  { secret: 'Phone', hint: 'Call', theme: 'objects' },
  { secret: 'Laptop', hint: 'Computer', theme: 'objects' },
  { secret: 'Watch', hint: 'Time', theme: 'objects' },
  { secret: 'Camera', hint: 'Photo', theme: 'objects' },
  { secret: 'Pen', hint: 'Write', theme: 'objects' },
  { secret: 'Backpack', hint: 'Carry', theme: 'objects' },
  { secret: 'Bicycle', hint: 'Ride', theme: 'objects' },
  { secret: 'Key', hint: 'Lock', theme: 'objects' },
  { secret: 'Glasses', hint: 'Vision', theme: 'objects' },
  { secret: 'Umbrella', hint: 'Rain', theme: 'objects' },
  { secret: 'Wallet', hint: 'Money', theme: 'objects' },
  { secret: 'Chair', hint: 'Sit', theme: 'objects' },
  { secret: 'Table', hint: 'Surface', theme: 'objects' },
  { secret: 'Book', hint: 'Read', theme: 'objects' },
  { secret: 'Shoes', hint: 'Feet', theme: 'objects' },
  { secret: 'Bottle', hint: 'Drink', theme: 'objects' },
  { secret: 'Headphones', hint: 'Music', theme: 'objects' },
  { secret: 'Clock', hint: 'Time', theme: 'objects' },
  { secret: 'Lamp', hint: 'Light', theme: 'objects' },
  { secret: 'Mirror', hint: 'Reflection', theme: 'objects' },
  { secret: 'Scissors', hint: 'Cut', theme: 'objects' },
  { secret: 'Bag', hint: 'Carry', theme: 'objects' },
  { secret: 'Spoon', hint: 'Eat', theme: 'objects' },
  { secret: 'Fan', hint: 'Air', theme: 'objects' },
  { secret: 'Television', hint: 'Watch', theme: 'objects' },
  { secret: 'Microwave', hint: 'Heat', theme: 'objects' },
  { secret: 'Refrigerator', hint: 'Cold', theme: 'objects' },
  { secret: 'Candle', hint: 'Wax', theme: 'objects' },
  { secret: 'Brush', hint: 'Hair', theme: 'objects' },
  { secret: 'Knife', hint: 'Cut', theme: 'objects' },
  { secret: 'Fork', hint: 'Eat', theme: 'objects' },
  { secret: 'Plate', hint: 'Food', theme: 'objects' },
  { secret: 'Cup', hint: 'Drink', theme: 'objects' },
  { secret: 'Pillow', hint: 'Sleep', theme: 'objects' },
  { secret: 'Blanket', hint: 'Warm', theme: 'objects' },
  { secret: 'Ruler', hint: 'Measure', theme: 'objects' },
  { secret: 'Eraser', hint: 'Remove', theme: 'objects' },
  { secret: 'Notebook', hint: 'Write', theme: 'objects' },
  { secret: 'Pen', hint: 'Write', theme: 'objects' },
  { secret: 'Pencil', hint: 'Draw', theme: 'objects' },
  { secret: 'Glue', hint: 'Stick', theme: 'objects' },
  { secret: 'Tape', hint: 'Stick', theme: 'objects' },
  { secret: 'Calculator', hint: 'Numbers', theme: 'objects' },
  { secret: 'Wallet', hint: 'Cash', theme: 'objects' },
  { secret: 'Backpack', hint: 'Carry', theme: 'objects' },
  { secret: 'Keychain', hint: 'Keys', theme: 'objects' },
  { secret: 'Wallet', hint: 'Cards', theme: 'objects' },
  { secret: 'Glasses', hint: 'See', theme: 'objects' },
  { secret: 'Umbrella', hint: 'Rain', theme: 'objects' },
  { secret: 'Phone Charger', hint: 'Power', theme: 'objects' },
  { secret: 'Keyboard', hint: 'Type', theme: 'objects' },
  { secret: 'Mouse', hint: 'Click', theme: 'objects' },
  { secret: 'Headset', hint: 'Listen', theme: 'objects' },
  { secret: 'Watch', hint: 'Time', theme: 'objects' },
  { secret: 'Wallet', hint: 'Money', theme: 'objects' },
  { secret: 'Suitcase', hint: 'Travel', theme: 'objects' },
  { secret: 'Towel', hint: 'Dry', theme: 'objects' },
  { secret: 'Comb', hint: 'Hair', theme: 'objects' },
  { secret: 'Brush', hint: 'Paint', theme: 'objects' },
  { secret: 'Bottle Opener', hint: 'Open', theme: 'objects' },
  { secret: 'Flashlight', hint: 'Light', theme: 'objects' },
  { secret: 'Sunglasses', hint: 'Shade', theme: 'objects' },
  { secret: 'Table', hint: 'Furniture', theme: 'objects' },
  { secret: 'Chair', hint: 'Sit', theme: 'objects' },
  { secret: 'Lamp', hint: 'Light', theme: 'objects' },
  { secret: 'Couch', hint: 'Comfort', theme: 'objects' },
  { secret: 'Door', hint: 'Entry', theme: 'objects' },
  { secret: 'Window', hint: 'Glass', theme: 'objects' },
  { secret: 'Fridge', hint: 'Cold', theme: 'objects' },
  { secret: 'Oven', hint: 'Heat', theme: 'objects' },
  { secret: 'Sink', hint: 'Water', theme: 'objects' },
  { secret: 'Clock', hint: 'Time', theme: 'objects' },

  // Animals
  { secret: 'Dog', hint: 'Bark', theme: 'animals' },
  { secret: 'Cat', hint: 'Meow', theme: 'animals' },
  { secret: 'Elephant', hint: 'Trunk', theme: 'animals' },
  { secret: 'Lion', hint: 'Cat', theme: 'animals' },
  { secret: 'Tiger', hint: 'Stripe', theme: 'animals' },
  { secret: 'Horse', hint: 'Gallop', theme: 'animals' },
  { secret: 'Monkey', hint: 'Banana', theme: 'animals' },
  { secret: 'Bear', hint: 'Honey', theme: 'animals' },
  { secret: 'Dolphin', hint: 'Ocean', theme: 'animals' },
  { secret: 'Owl', hint: 'Night', theme: 'animals' },
  { secret: 'Rabbit', hint: 'Carrot', theme: 'animals' },
  { secret: 'Fox', hint: 'Clever', theme: 'animals' },
  { secret: 'Wolf', hint: 'Howl', theme: 'animals' },
  { secret: 'Giraffe', hint: 'Neck', theme: 'animals' },
  { secret: 'Zebra', hint: 'Stripes', theme: 'animals' },
  { secret: 'Kangaroo', hint: 'Pouch', theme: 'animals' },
  { secret: 'Panda', hint: 'Bamboo', theme: 'animals' },
  { secret: 'Penguin', hint: 'Waddle', theme: 'animals' },
  { secret: 'Seal', hint: 'Flippers', theme: 'animals' },
  { secret: 'Shark', hint: 'Teeth', theme: 'animals' },
  { secret: 'Whale', hint: 'Blowhole', theme: 'animals' },
  { secret: 'Frog', hint: 'Jump', theme: 'animals' },
  { secret: 'Snake', hint: 'Slither', theme: 'animals' },
  { secret: 'Crab', hint: 'Claws', theme: 'animals' },
  { secret: 'Octopus', hint: 'Tentacles', theme: 'animals' },
  { secret: 'Eagle', hint: 'Fly', theme: 'animals' },
  { secret: 'Parrot', hint: 'Talk', theme: 'animals' },
  { secret: 'Peacock', hint: 'Feathers', theme: 'animals' },
  { secret: 'Butterfly', hint: 'Wings', theme: 'animals' },
  { secret: 'Bee', hint: 'Honey', theme: 'animals' },
  { secret: 'Ant', hint: 'Colony', theme: 'animals' },
  { secret: 'Crocodile', hint: 'Teeth', theme: 'animals' },
  { secret: 'Hippo', hint: 'Water', theme: 'animals' },
  { secret: 'Camel', hint: 'Hump', theme: 'animals' },
  { secret: 'Goat', hint: 'Horns', theme: 'animals' },
  { secret: 'Sheep', hint: 'Wool', theme: 'animals' },
  { secret: 'Pig', hint: 'Mud', theme: 'animals' },
  { secret: 'Chicken', hint: 'Eggs', theme: 'animals' },
  { secret: 'Duck', hint: 'Quack', theme: 'animals' },
  { secret: 'Turkey', hint: 'Feathers', theme: 'animals' },
  { secret: 'Rabbit', hint: 'Hopping', theme: 'animals' },
  { secret: 'Moose', hint: 'Antlers', theme: 'animals' },
  { secret: 'Deer', hint: 'Forest', theme: 'animals' },
  { secret: 'Bat', hint: 'Echo', theme: 'animals' },
  { secret: 'Otter', hint: 'River', theme: 'animals' },
  { secret: 'Beaver', hint: 'Dam', theme: 'animals' },
  { secret: 'Raccoon', hint: 'Mask', theme: 'animals' },
  { secret: 'Squirrel', hint: 'Nuts', theme: 'animals' },
  { secret: 'Lizard', hint: 'Tail', theme: 'animals' },
  { secret: 'Frog', hint: 'Croak', theme: 'animals' },
  { secret: 'Hawk', hint: 'Prey', theme: 'animals' },
  { secret: 'Seagull', hint: 'Beach', theme: 'animals' },
  { secret: 'Crane', hint: 'Long Neck', theme: 'animals' },
  { secret: 'Flamingo', hint: 'Pink', theme: 'animals' },
  { secret: 'Toucan', hint: 'Beak', theme: 'animals' },
  { secret: 'Camel', hint: 'Desert', theme: 'animals' },
  { secret: 'Walrus', hint: 'Tusks', theme: 'animals' },
  { secret: 'Chameleon', hint: 'Color', theme: 'animals' },
  { secret: 'Hippopotamus', hint: 'River', theme: 'animals' },
  { secret: 'Orangutan', hint: 'Tree', theme: 'animals' },

  // Vehicles
  { secret: 'Car', hint: 'Drive', theme: 'vehicles' },
  { secret: 'Airplane', hint: 'Fly', theme: 'vehicles' },
  { secret: 'Boat', hint: 'Sail', theme: 'vehicles' },
  { secret: 'Train', hint: 'Track', theme: 'vehicles' },
  { secret: 'Motorcycle', hint: 'Ride', theme: 'vehicles' },
  { secret: 'Bicycle', hint: 'Pedal', theme: 'vehicles' },
  { secret: 'Truck', hint: 'Cargo', theme: 'vehicles' },
  { secret: 'Helicopter', hint: 'Rotor', theme: 'vehicles' },
  { secret: 'Submarine', hint: 'Underwater', theme: 'vehicles' },
  { secret: 'Bus', hint: 'Route', theme: 'vehicles' },

  // Nature
  { secret: 'Tree', hint: 'Leaves', theme: 'nature' },
  { secret: 'River', hint: 'Water', theme: 'nature' },
  { secret: 'Mountain', hint: 'Peak', theme: 'nature' },
  { secret: 'Ocean', hint: 'Salt', theme: 'nature' },
  { secret: 'Flower', hint: 'Petal', theme: 'nature' },
  { secret: 'Rain', hint: 'Drops', theme: 'nature' },
  { secret: 'Sun', hint: 'Light', theme: 'nature' },
  { secret: 'Moon', hint: 'Night', theme: 'nature' },
  { secret: 'Snow', hint: 'Cold', theme: 'nature' },
  { secret: 'Wind', hint: 'Breeze', theme: 'nature' },
  { secret: 'Hedge', hint: 'Bush', theme: 'nature' },
  { secret: 'Fungus', hint: 'Mushroom', theme: 'nature' },
  { secret: 'Northern Lights', hint: 'Aurora', theme: 'nature' },
  { secret: 'Wheat', hint: 'Grain', theme: 'nature' },
  { secret: 'Pterodactyl', hint: 'Dinosaur', theme: 'nature' },
  { secret: 'Dandelion', hint: 'Seeds', theme: 'nature' },
  { secret: 'Toad', hint: 'Amphibian', theme: 'nature' },
  { secret: 'Cucumber', hint: 'Vegetable', theme: 'nature' },
  { secret: 'Sand', hint: 'Beach', theme: 'nature' },
  { secret: 'Rock', hint: 'Stone', theme: 'nature' },
  { secret: 'Leaf', hint: 'Green', theme: 'nature' },
  { secret: 'Acorn', hint: 'Oak', theme: 'nature' },
  { secret: 'Mushroom', hint: 'Fungi', theme: 'nature' },
  { secret: 'Pinecone', hint: 'Tree', theme: 'nature' },
  { secret: 'Berry', hint: 'Fruit', theme: 'nature' },
  { secret: 'Vine', hint: 'Climb', theme: 'nature' },
  { secret: 'Moss', hint: 'Green', theme: 'nature' },
  { secret: 'Ivy', hint: 'Climbing', theme: 'nature' },
  { secret: 'Shell', hint: 'Beach', theme: 'nature' },
  { secret: 'Clam', hint: 'Shell', theme: 'nature' },
  { secret: 'Coral', hint: 'Reef', theme: 'nature' },
  { secret: 'Pebble', hint: 'Stone', theme: 'nature' },
  { secret: 'Stream', hint: 'Water', theme: 'nature' },
  { secret: 'Hill', hint: 'Slope', theme: 'nature' },
  { secret: 'Bush', hint: 'Leaves', theme: 'nature' },
  { secret: 'Sapling', hint: 'Young', theme: 'nature' },
  { secret: 'Butterfly', hint: 'Wings', theme: 'nature' },
  { secret: 'Bee', hint: 'Honey', theme: 'nature' },
  { secret: 'Caterpillar', hint: 'Insect', theme: 'nature' },
  { secret: 'Snail', hint: 'Shell', theme: 'nature' },
  { secret: 'Spider', hint: 'Web', theme: 'nature' },
  { secret: 'Ant', hint: 'Colony', theme: 'nature' },
  { secret: 'Grass', hint: 'Green', theme: 'nature' },
  { secret: 'Bush', hint: 'Shrub', theme: 'nature' },
  { secret: 'Flowerpot', hint: 'Plant', theme: 'nature' },
  { secret: 'Orchid', hint: 'Plant', theme: 'nature' },
  { secret: 'Sunflower', hint: 'Seeds', theme: 'nature' },
  { secret: 'Oak', hint: 'Tree', theme: 'nature' },
  { secret: 'Maple', hint: 'Leaves', theme: 'nature' },
  { secret: 'Birch', hint: 'Bark', theme: 'nature' },
  { secret: 'Willow', hint: 'Tree', theme: 'nature' },
  { secret: 'Cactus', hint: 'Desert', theme: 'nature' },
  { secret: 'Seashell', hint: 'Beach', theme: 'nature' },
  { secret: 'Daisy', hint: 'Flower', theme: 'nature' },
  { secret: 'Tulip', hint: 'Flower', theme: 'nature' },

  // Sports
  { secret: 'Football', hint: 'Goal', theme: 'sports' },
  { secret: 'Basketball', hint: 'Hoop', theme: 'sports' },
  { secret: 'Tennis', hint: 'Racket', theme: 'sports' },
  { secret: 'Baseball', hint: 'Bat', theme: 'sports' },
  { secret: 'Golf', hint: 'Hole', theme: 'sports' },
  { secret: 'Swimming', hint: 'Pool', theme: 'sports' },
  { secret: 'Cycling', hint: 'Helmet', theme: 'sports' },
  { secret: 'Running', hint: 'Track', theme: 'sports' },
  { secret: 'Boxing', hint: 'Gloves', theme: 'sports' },
  { secret: 'Skiing', hint: 'Snow', theme: 'sports' },
  { secret: 'Soccer', hint: 'Goal', theme: 'sports' },
  { secret: 'Volleyball', hint: 'Net', theme: 'sports' },
  { secret: 'Cricket', hint: 'Wicket', theme: 'sports' },
  { secret: 'Rugby', hint: 'Try', theme: 'sports' },
  { secret: 'Hockey', hint: 'Stick', theme: 'sports' },
  { secret: 'Badminton', hint: 'Shuttle', theme: 'sports' },
  { secret: 'Table Tennis', hint: 'Paddle', theme: 'sports' },
  { secret: 'Skateboarding', hint: 'Ramp', theme: 'sports' },
  { secret: 'Snowboarding', hint: 'Slope', theme: 'sports' },
  { secret: 'Surfing', hint: 'Wave', theme: 'sports' },
  { secret: 'Sailing', hint: 'Boat', theme: 'sports' },
  { secret: 'Archery', hint: 'Bow', theme: 'sports' },
  { secret: 'Gymnastics', hint: 'Balance', theme: 'sports' },
  { secret: 'Wrestling', hint: 'Mat', theme: 'sports' },
  { secret: 'Judo', hint: 'Throw', theme: 'sports' },
  { secret: 'Karate', hint: 'Kick', theme: 'sports' },
  { secret: 'Fencing', hint: 'Sword', theme: 'sports' },
  { secret: 'Diving', hint: 'Platform', theme: 'sports' },
  { secret: 'Horse Riding', hint: 'Saddle', theme: 'sports' },
  { secret: 'Bowling', hint: 'Pins', theme: 'sports' },
  { secret: 'Ping Pong', hint: 'Ball', theme: 'sports' },
  { secret: 'Marathon', hint: 'Distance', theme: 'sports' },
  { secret: 'Triathlon', hint: 'Three', theme: 'sports' },
  { secret: 'Skating', hint: 'Ice', theme: 'sports' },
  { secret: 'Lacrosse', hint: 'Stick', theme: 'sports' },
  { secret: 'Racing', hint: 'Speed', theme: 'sports' },
  { secret: 'Weightlifting', hint: 'Barbell', theme: 'sports' },
  { secret: 'Kickboxing', hint: 'Punch', theme: 'sports' },
  { secret: 'Snowball Fight', hint: 'Winter', theme: 'sports' },
  { secret: 'Orienteering', hint: 'Map', theme: 'sports' },
  
  // Tech
  { secret: 'Computer', hint: 'Keyboard', theme: 'technology' },
  { secret: 'Smartphone', hint: 'Apps', theme: 'technology' },
  { secret: 'Internet', hint: 'Web', theme: 'technology' },
  { secret: 'Email', hint: 'Inbox', theme: 'technology' },
  { secret: 'Software', hint: 'Program', theme: 'technology' },
  { secret: 'Hardware', hint: 'Device', theme: 'technology' },
  { secret: 'Server', hint: 'Data', theme: 'technology' },
  { secret: 'Cloud', hint: 'Storage', theme: 'technology' },
  { secret: 'Battery', hint: 'Power', theme: 'technology' },
  { secret: 'Screen', hint: 'Display', theme: 'technology' },
  { secret: 'Laptop', hint: 'Portable', theme: 'technology' },
  { secret: 'Tablet', hint: 'Touch', theme: 'technology' },
  { secret: 'Router', hint: 'Wi-Fi', theme: 'technology' },
  { secret: 'Modem', hint: 'Internet', theme: 'technology' },
  { secret: 'Printer', hint: 'Paper', theme: 'technology' },
  { secret: 'Scanner', hint: 'Image', theme: 'technology' },
  { secret: 'Keyboard', hint: 'Type', theme: 'technology' },
  { secret: 'Mouse', hint: 'Click', theme: 'technology' },
  { secret: 'Monitor', hint: 'Screen', theme: 'technology' },
  { secret: 'Headphones', hint: 'Sound', theme: 'technology' },
  { secret: 'Microphone', hint: 'Voice', theme: 'technology' },
  { secret: 'Camera', hint: 'Photo', theme: 'technology' },
  { secret: 'Speaker', hint: 'Audio', theme: 'technology' },
  { secret: 'Smartwatch', hint: 'Time', theme: 'technology' },
  { secret: 'Charger', hint: 'Power', theme: 'technology' },
  { secret: 'USB', hint: 'Drive', theme: 'technology' },
  { secret: 'Cable', hint: 'Wire', theme: 'technology' },
  { secret: 'App', hint: 'Mobile', theme: 'technology' },
  { secret: 'Website', hint: 'Page', theme: 'technology' },
  { secret: 'Login', hint: 'Username', theme: 'technology' },
  { secret: 'Password', hint: 'Secret', theme: 'technology' },
  { secret: 'Cloud Storage', hint: 'Online', theme: 'technology' },
  { secret: 'Database', hint: 'Tables', theme: 'technology' },
  { secret: 'Algorithm', hint: 'Steps', theme: 'technology' },
  { secret: 'Programming', hint: 'Code', theme: 'technology' },
  { secret: 'Firewall', hint: 'Protect', theme: 'technology' },
  { secret: 'Antivirus', hint: 'Scan', theme: 'technology' },
  { secret: 'Bluetooth', hint: 'Wireless', theme: 'technology' },
  { secret: 'Wi-Fi', hint: 'Signal', theme: 'technology' },
  { secret: 'Drone', hint: 'Fly', theme: 'technology' },
  { secret: 'Robot', hint: 'Automaton', theme: 'technology' },
  { secret: 'VR Headset', hint: 'Virtual', theme: 'technology' },
  { secret: 'Smart Home', hint: 'Automation', theme: 'technology' },
  { secret: 'Printer Ink', hint: 'Cartridge', theme: 'technology' },
  { secret: 'Touchscreen', hint: 'Finger', theme: 'technology' },
  { secret: 'E-reader', hint: 'Books', theme: 'technology' },
  { secret: 'Game Console', hint: 'Controller', theme: 'technology' },
  { secret: 'Streaming', hint: 'Video', theme: 'technology' },
  { secret: 'Laptop Bag', hint: 'Carry', theme: 'technology' },
  { secret: 'Remote', hint: 'Control', theme: 'technology' },
  { secret: 'Smart TV', hint: 'Apps', theme: 'technology' },
  { secret: 'Keyboard Shortcuts', hint: 'Keys', theme: 'technology' },
  { secret: 'Monitor Stand', hint: 'Elevate', theme: 'technology' },
  { secret: 'Projector', hint: 'Display', theme: 'technology' },
  { secret: 'Headset', hint: 'Audio', theme: 'technology' },
  { secret: 'Touchpad', hint: 'Swipe', theme: 'technology' },
  { secret: 'MicroSD', hint: 'Storage', theme: 'technology' },
  { secret: 'Ethernet', hint: 'Cable', theme: 'technology' },
  { secret: 'Smart Light', hint: 'Lamp', theme: 'technology' },

   // Famous People (new)
  { secret: 'Albert Einstein', hint: 'Relativity', theme: 'famous-people' },
  { secret: 'Leonardo da Vinci', hint: 'Renaissance', theme: 'famous-people' },
  { secret: 'William Shakespeare', hint: 'Playwright', theme: 'famous-people' },
  { secret: 'Marie Curie', hint: 'Radium', theme: 'famous-people' },
  { secret: 'Martin Luther King Jr.', hint: 'Civil Rights', theme: 'famous-people' },
  { secret: 'Nelson Mandela', hint: 'Apartheid', theme: 'famous-people' },
  { secret: 'Steve Jobs', hint: 'Apple', theme: 'famous-people' },
  { secret: 'Michael Jordan', hint: 'Basketball', theme: 'famous-people' },
  { secret: 'Elvis Presley', hint: 'Rock and Roll', theme: 'famous-people' },
  { secret: 'Queen Elizabeth II', hint: 'Monarchy', theme: 'famous-people' },
  { secret: 'Neil Armstrong', hint: 'Moon', theme: 'famous-people' },
  { secret: 'Martin Clunes', hint: 'Actor', theme: 'famous-people' },
  { secret: 'Homer', hint: 'Epic Poems', theme: 'famous-people' },
  { secret: 'Gandalf', hint: 'Wizard', theme: 'famous-people' },
  { secret: 'Cleopatra', hint: 'Egypt', theme: 'famous-people' },
  { secret: 'Winston Churchill', hint: 'Prime Minister', theme: 'famous-people' },
  { secret: 'Abraham Lincoln', hint: 'President', theme: 'famous-people' },
  { secret: 'Julius Caesar', hint: 'Rome', theme: 'famous-people' },
  { secret: 'Charles Darwin', hint: 'Evolution', theme: 'famous-people' },
  { secret: 'Amelia Earhart', hint: 'Aviation', theme: 'famous-people' },
  { secret: 'Mozart', hint: 'Composer', theme: 'famous-people' },
  { secret: 'Beethoven', hint: 'Symphony', theme: 'famous-people' },
  { secret: 'Pablo Picasso', hint: 'Painter', theme: 'famous-people' },
  { secret: 'Frida Kahlo', hint: 'Art', theme: 'famous-people' },
  { secret: 'Oprah Winfrey', hint: 'Talk Show', theme: 'famous-people' },
  { secret: 'Madonna', hint: 'Pop Star', theme: 'famous-people' },
  { secret: 'Elon Musk', hint: 'SpaceX', theme: 'famous-people' },
  { secret: 'Serena Williams', hint: 'Tennis', theme: 'famous-people' },
  { secret: 'Tiger Woods', hint: 'Golf', theme: 'famous-people' },
  { secret: 'Harry Potter', hint: 'Wizard', theme: 'famous-people' },
  { secret: 'Luke Skywalker', hint: 'Star Wars', theme: 'famous-people' },
  { secret: 'Darth Vader', hint: 'Star Wars', theme: 'famous-people' },
  { secret: 'Indiana Jones', hint: 'Adventure', theme: 'famous-people' },
  { secret: 'James Bond', hint: 'Spy', theme: 'famous-people' },
  { secret: 'Sherlock Holmes', hint: 'Detective', theme: 'famous-people' },
  { secret: 'Marie Antoinette', hint: 'France', theme: 'famous-people' },
  { secret: 'George Washington', hint: 'President', theme: 'famous-people' },
  { secret: 'Joan of Arc', hint: 'Warrior', theme: 'famous-people' },
  { secret: 'Hercules', hint: 'Strength', theme: 'famous-people' },
  { secret: 'Robin Hood', hint: 'Archer', theme: 'famous-people' },
  { secret: 'Mahatma Gandhi', hint: 'Nonviolence', theme: 'famous-people' },
  { secret: 'Nelson Mandela', hint: 'Freedom', theme: 'famous-people' },
  { secret: 'Anne Frank', hint: 'Diary', theme: 'famous-people' },
  { secret: 'Walt Disney', hint: 'Animation', theme: 'famous-people' },
  { secret: 'Charlie Chaplin', hint: 'Comedy', theme: 'famous-people' },
  { secret: 'Vincent van Gogh', hint: 'Starry Night', theme: 'famous-people' },
  { secret: 'Confucius', hint: 'Philosophy', theme: 'famous-people' },
  { secret: 'Socrates', hint: 'Philosophy', theme: 'famous-people' },
  { secret: 'Buddha', hint: 'Enlightenment', theme: 'famous-people' },
  { secret: 'Mona Lisa', hint: 'Painting', theme: 'famous-people' },
  { secret: 'Cardi B', hint: 'Rapper', theme: 'famous-people' },
  { secret: 'Eddie Hall', hint: 'Strongman', theme: 'famous-people' },
  { secret: 'Bugs Bunny', hint: 'Cartoon', theme: 'famous-people' },
  { secret: 'Michael Jackson', hint: 'Moonwalk', theme: 'famous-people' },
  { secret: 'Mona Lisa', hint: 'Painting', theme: 'famous-people' },
  { secret: 'Diego Maradona', hint: 'Football', theme: 'famous-people' },
  { secret: 'Nicolas Cage', hint: 'Actor', theme: 'famous-people' },
  { secret: 'Katy Perry', hint: 'Singer', theme: 'famous-people' },
  { secret: 'Ariana Grande', hint: 'Singer', theme: 'famous-people' },
  { secret: 'Elon Musk', hint: 'Tesla', theme: 'famous-people' },
  { secret: 'Cristiano Ronaldo', hint: 'Football', theme: 'famous-people' },
  { secret: 'Lionel Messi', hint: 'Football', theme: 'famous-people' },
  { secret: 'Oprah Winfrey', hint: 'Talk Show', theme: 'famous-people' },
  { secret: 'Taylor Swift', hint: 'Singer', theme: 'famous-people' },
  { secret: 'Dwayne Johnson', hint: 'Wrestler', theme: 'famous-people' },
  { secret: 'Kim Kardashian', hint: 'Reality TV', theme: 'famous-people' },
  { secret: 'Bill Gates', hint: 'Microsoft', theme: 'famous-people' },
  { secret: 'Mark Zuckerberg', hint: 'Facebook', theme: 'famous-people' },
  { secret: 'Beyoncé', hint: 'Singer', theme: 'famous-people' },
  { secret: 'Elvis Presley', hint: 'Rock', theme: 'famous-people' },
  { secret: 'Madonna', hint: 'Pop', theme: 'famous-people' },
  { secret: 'Homer Simpson', hint: 'Cartoon', theme: 'famous-people' },
  { secret: 'Bart Simpson', hint: 'Cartoon', theme: 'famous-people' },
  { secret: 'SpongeBob', hint: 'Cartoon', theme: 'famous-people' },
  { secret: 'Shrek', hint: 'Ogre', theme: 'famous-people' },
  { secret: 'Fiona', hint: 'Princess', theme: 'famous-people' },
  { secret: 'Harry Potter', hint: 'Wizard', theme: 'famous-people' },
  { secret: 'Hermione Granger', hint: 'Witch', theme: 'famous-people' },
  { secret: 'Ron Weasley', hint: 'Wizard', theme: 'famous-people' },
  { secret: 'Darth Vader', hint: 'Star Wars', theme: 'famous-people' },
  { secret: 'Luke Skywalker', hint: 'Star Wars', theme: 'famous-people' },
  { secret: 'Yoda', hint: 'Jedi', theme: 'famous-people' },
  { secret: 'Gandalf', hint: 'Wizard', theme: 'famous-people' },
  { secret: 'Frodo', hint: 'Hobbit', theme: 'famous-people' },
  { secret: 'Samwise Gamgee', hint: 'Hobbit', theme: 'famous-people' },
  { secret: 'Spider-Man', hint: 'Superhero', theme: 'famous-people' },
  { secret: 'Batman', hint: 'Superhero', theme: 'famous-people' },
  { secret: 'Superman', hint: 'Superhero', theme: 'famous-people' },
  { secret: 'Wonder Woman', hint: 'Superhero', theme: 'famous-people' },
  { secret: 'Iron Man', hint: 'Avenger', theme: 'famous-people' },
  { secret: 'Captain America', hint: 'Avenger', theme: 'famous-people' },
  { secret: 'Black Panther', hint: 'Marvel', theme: 'famous-people' },
  { secret: 'Thor', hint: 'Marvel', theme: 'famous-people' },
  { secret: 'Hulk', hint: 'Marvel', theme: 'famous-people' },
  { secret: 'Deadpool', hint: 'Mercenary', theme: 'famous-people' },
  { secret: 'Wolverine', hint: 'X-Men', theme: 'famous-people' },
  { secret: 'Elsa', hint: 'Frozen', theme: 'famous-people' },
  { secret: 'Anna', hint: 'Frozen', theme: 'famous-people' },
  { secret: 'Moana', hint: 'Disney', theme: 'famous-people' },
  { secret: 'Simba', hint: 'Lion King', theme: 'famous-people' },

   // Brands/Logos (new)
  { secret: 'Apple', hint: 'Bitten Fruit', theme: 'brands' },
  { secret: 'Nike', hint: 'Swoosh', theme: 'brands' },
  { secret: 'McDonalds', hint: 'Golden Arches', theme: 'brands' },
  { secret: 'Coca-Cola', hint: 'Red Can', theme: 'brands' },
  { secret: 'Google', hint: 'Search Engine', theme: 'brands' },
  { secret: 'Amazon', hint: 'Smile Arrow', theme: 'brands' },
  { secret: 'Toyota', hint: 'Japanese Cars', theme: 'brands' },
  { secret: 'Samsung', hint: 'Galaxy', theme: 'brands' },
  { secret: 'Adidas', hint: 'Three Stripes', theme: 'brands' },
  { secret: 'Starbucks', hint: 'Mermaid', theme: 'brands' },
  { secret: 'Facebook', hint: 'Blue F', theme: 'brands' },
  { secret: 'Twitter', hint: 'Bird', theme: 'brands' },
  { secret: 'Instagram', hint: 'Camera', theme: 'brands' },
  { secret: 'Microsoft', hint: 'Windows', theme: 'brands' },
  { secret: 'Disney', hint: 'Castle', theme: 'brands' },
  { secret: 'Pepsi', hint: 'Blue and Red', theme: 'brands' },
  { secret: 'Netflix', hint: 'Red N', theme: 'brands' },
  { secret: 'KFC', hint: 'Colonel', theme: 'brands' },
  { secret: 'Burger King', hint: 'Crown', theme: 'brands' },
  { secret: 'LEGO', hint: 'Bricks', theme: 'brands' },
  { secret: 'Shell', hint: 'Yellow Red', theme: 'brands' },
  { secret: 'Puma', hint: 'Jumping Cat', theme: 'brands' },
  { secret: 'Audi', hint: 'Four Rings', theme: 'brands' },
  { secret: 'Mercedes', hint: 'Three Star', theme: 'brands' },
  { secret: 'BMW', hint: 'Blue White', theme: 'brands' },
  { secret: 'Louis Vuitton', hint: 'Monogram', theme: 'brands' },
  { secret: 'Gucci', hint: 'Double G', theme: 'brands' },
  { secret: 'Prada', hint: 'Luxury', theme: 'brands' },
  { secret: 'Visa', hint: 'Credit Card', theme: 'brands' },
  { secret: 'MasterCard', hint: 'Two Circles', theme: 'brands' },
  { secret: 'YouTube', hint: 'Play Button', theme: 'brands' },
  { secret: 'TikTok', hint: 'Music Note', theme: 'brands' },
  { secret: 'Snapchat', hint: 'Ghost', theme: 'brands' },
  { secret: 'Red Bull', hint: 'Energy Drink', theme: 'brands' },
  { secret: 'Harley-Davidson', hint: 'Motorcycles', theme: 'brands' },
  { secret: 'IKEA', hint: 'Furniture', theme: 'brands' },
  { secret: 'Canon', hint: 'Camera', theme: 'brands' },
  { secret: 'Sony', hint: 'Electronics', theme: 'brands' },
  { secret: 'LEVI\'s', hint: 'Jeans', theme: 'brands' },
  { secret: 'H&M', hint: 'Fashion', theme: 'brands' },
  { secret: 'Dior', hint: 'Luxury', theme: 'brands' },
  { secret: 'Rolex', hint: 'Watches', theme: 'brands' },
  { secret: 'Nintendo', hint: 'Games', theme: 'brands' },
  { secret: 'PlayStation', hint: 'Console', theme: 'brands' },
  { secret: 'Xbox', hint: 'Console', theme: 'brands' },
  { secret: 'TikTok', hint: 'App', theme: 'brands' },
  { secret: 'LinkedIn', hint: 'Business', theme: 'brands' },
  { secret: 'Snapchat', hint: 'Ghost', theme: 'brands' },
  { secret: 'Amazon Prime', hint: 'Video', theme: 'brands' },
  { secret: 'WhatsApp', hint: 'Green Phone', theme: 'brands' },
  { secret: 'Pinterest', hint: 'P Logo', theme: 'brands' },
  { secret: 'PayPal', hint: 'Payments', theme: 'brands' },
  { secret: 'Uber', hint: 'Ride', theme: 'brands' },
  { secret: 'Airbnb', hint: 'A Logo', theme: 'brands' },
  { secret: 'TikTok', hint: 'Video App', theme: 'brands' },
  { secret: 'Snapchat', hint: 'Yellow Ghost', theme: 'brands' },
  { secret: 'eBay', hint: 'Online Market', theme: 'brands' },
  { secret: 'Spotify', hint: 'Music', theme: 'brands' },
  { secret: 'TikTok', hint: 'Social Media', theme: 'brands' },

  { secret: 'France', hint: 'Paris', theme: 'locations' },
  { secret: 'Japan', hint: 'Tokyo', theme: 'locations' },
  { secret: 'United States', hint: 'Washington DC', theme: 'locations' },
  { secret: 'Brazil', hint: 'Carnival', theme: 'locations' },
  { secret: 'Australia', hint: 'Sydney', theme: 'locations' },
  { secret: 'Egypt', hint: 'Cairo', theme: 'locations' },
  { secret: 'Italy', hint: 'Rome', theme: 'locations' },
  { secret: 'China', hint: 'Beijing', theme: 'locations' },
  { secret: 'India', hint: 'New Delhi', theme: 'locations' },
  { secret: 'Canada', hint: 'Ottawa', theme: 'locations' },
  { secret: 'Mexico', hint: 'Mexico City', theme: 'locations' },
  { secret: 'Russia', hint: 'Moscow', theme: 'locations' },
  { secret: 'United Kingdom', hint: 'London', theme: 'locations' },
  { secret: 'Germany', hint: 'Berlin', theme: 'locations' },
  { secret: 'Spain', hint: 'Madrid', theme: 'locations' },
  { secret: 'Greece', hint: 'Athens', theme: 'locations' },
  { secret: 'South Africa', hint: 'Cape Town', theme: 'locations' },
  { secret: 'Thailand', hint: 'Bangkok', theme: 'locations' },
  { secret: 'Turkey', hint: 'Ankara', theme: 'locations' },
  { secret: 'Sweden', hint: 'Stockholm', theme: 'locations' },
  { secret: 'Norway', hint: 'Oslo', theme: 'locations' },
  { secret: 'Netherlands', hint: 'Amsterdam', theme: 'locations' },
  { secret: 'Argentina', hint: 'Buenos Aires', theme: 'locations' },
  { secret: 'Morocco', hint: 'Marrakech', theme: 'locations' },
  { secret: 'South Korea', hint: 'Seoul', theme: 'locations' },
  { secret: 'North Korea', hint: 'Pyongyang', theme: 'locations' },
  { secret: 'Vietnam', hint: 'Hanoi', theme: 'locations' },
  { secret: 'Singapore', hint: 'Marina Bay', theme: 'locations' },
  { secret: 'Dubai', hint: 'Skyscrapers', theme: 'locations' },
  { secret: 'Istanbul', hint: 'Bosphorus', theme: 'locations' },
  { secret: 'Paris', hint: 'Louvre', theme: 'locations' },
  { secret: 'New York', hint: 'Times Square', theme: 'locations' },
  { secret: 'Tokyo', hint: 'Shibuya Crossing', theme: 'locations' },
  { secret: 'Rome', hint: 'Colosseum', theme: 'locations' },
  { secret: 'Cairo', hint: 'Nile', theme: 'locations' },
  { secret: 'Sydney', hint: 'Opera House', theme: 'locations' },
  { secret: 'Rio de Janeiro', hint: 'Christ the Redeemer', theme: 'locations' },
  { secret: 'Beijing', hint: 'Forbidden City', theme: 'locations' },
  { secret: 'Moscow', hint: 'Kremlin', theme: 'locations' },
  { secret: 'Barcelona', hint: 'Sagrada Familia', theme: 'locations' },
  { secret: 'Amsterdam', hint: 'Canals', theme: 'locations' },
  { secret: 'Venice', hint: 'Gondolas', theme: 'locations' },
  { secret: 'Lisbon', hint: 'Tram', theme: 'locations' },
  { secret: 'Bangkok', hint: 'Temples', theme: 'locations' },
  { secret: 'Havana', hint: 'Cigars', theme: 'locations' },
  { secret: 'Florence', hint: 'Duomo', theme: 'locations' },
  { secret: 'Prague', hint: 'Astronomical Clock', theme: 'locations' },
  { secret: 'Stockholm', hint: 'Archipelago', theme: 'locations' },
  { secret: 'Helsinki', hint: 'Sauna', theme: 'locations' },
  { secret: 'Jerusalem', hint: 'Western Wall', theme: 'locations' },
  { secret: 'Mecca', hint: 'Kaaba', theme: 'locations' },
  { secret: 'Mount Everest', hint: 'Highest Peak', theme: 'locations' },
  { secret: 'Fuji', hint: 'Volcano', theme: 'locations' },
  { secret: 'Notting Hill', hint: 'London', theme: 'locations' },
  { secret: 'Chelsea', hint: 'Football Club', theme: 'locations' },
  { secret: 'Seine', hint: 'River in Paris', theme: 'locations' },
  { secret: 'Thames', hint: 'River in London', theme: 'locations' },
  { secret: 'Niagara Falls', hint: 'Waterfall', theme: 'locations' },
  { secret: 'Grand Canyon', hint: 'Arizona', theme: 'locations' },

   // Science (new)
  { secret: 'Gravity', hint: 'Newton', theme: 'science' },
  { secret: 'DNA', hint: 'Double Helix', theme: 'science' },
  { secret: 'Atom', hint: 'Proton', theme: 'science' },
  { secret: 'Photosynthesis', hint: 'Plants', theme: 'science' },
  { secret: 'Evolution', hint: 'Darwin', theme: 'science' },
  { secret: 'Magnetism', hint: 'Poles', theme: 'science' },
  { secret: 'Electricity', hint: 'Current', theme: 'science' },
  { secret: 'Telescope', hint: 'Stars', theme: 'science' },
  { secret: 'Microscope', hint: 'Cells', theme: 'science' },
  { secret: 'Volcano', hint: 'Eruption', theme: 'science' },
  { secret: 'Black Hole', hint: 'Singularity', theme: 'science' },
  { secret: 'Neuron', hint: 'Brain', theme: 'science' },
  { secret: 'Planet', hint: 'Orbit', theme: 'science' },
  { secret: 'Galaxy', hint: 'Stars', theme: 'science' },
  { secret: 'Oxygen', hint: 'Breath', theme: 'science' },
  { secret: 'Hydrogen', hint: 'Water', theme: 'science' },
  { secret: 'Carbon', hint: 'Element', theme: 'science' },
  { secret: 'Fossil', hint: 'Ancient', theme: 'science' },
  { secret: 'Virus', hint: 'Infection', theme: 'science' },
  { secret: 'Bacteria', hint: 'Microbe', theme: 'science' },
  { secret: 'Solar System', hint: 'Planets', theme: 'science' },
  { secret: 'Comet', hint: 'Tail', theme: 'science' },
  { secret: 'Asteroid', hint: 'Rock', theme: 'science' },
  { secret: 'Magnet', hint: 'Attract', theme: 'science' },
  { secret: 'Circuit', hint: 'Electricity', theme: 'science' },
  { secret: 'Battery', hint: 'Power', theme: 'science' },
  { secret: 'Rocket', hint: 'Launch', theme: 'science' },
  { secret: 'Satellite', hint: 'Orbit', theme: 'science' },
  { secret: 'Atom', hint: 'Electron', theme: 'science' },
  { secret: 'Molecule', hint: 'Chemical', theme: 'science' },
  { secret: 'DNA', hint: 'Genes', theme: 'science' },
  { secret: 'RNA', hint: 'Messenger', theme: 'science' },
  { secret: 'Protein', hint: 'Amino Acid', theme: 'science' },
  { secret: 'Climate', hint: 'Weather', theme: 'science' },
  { secret: 'Energy', hint: 'Power', theme: 'science' },
  { secret: 'Force', hint: 'Push', theme: 'science' },
  { secret: 'Inertia', hint: 'Motion', theme: 'science' },
  { secret: 'Velocity', hint: 'Speed', theme: 'science' },
  { secret: 'Acceleration', hint: 'Change', theme: 'science' },
  { secret: 'Pressure', hint: 'Force/Area', theme: 'science' },
  { secret: 'Temperature', hint: 'Heat', theme: 'science' },
  { secret: 'Evaporation', hint: 'Water', theme: 'science' },
  { secret: 'Condensation', hint: 'Clouds', theme: 'science' },
  { secret: 'Gravity', hint: 'Falling', theme: 'science' },
  { secret: 'Magnetism', hint: 'Poles', theme: 'science' },
  { secret: 'Acid', hint: 'pH', theme: 'science' },
  { secret: 'Base', hint: 'pH', theme: 'science' },
  { secret: 'Neuron', hint: 'Synapse', theme: 'science' },
  { secret: 'Brain', hint: 'Thinking', theme: 'science' },
  { secret: 'Heart', hint: 'Pump', theme: 'science' },
  { secret: 'Lungs', hint: 'Breathing', theme: 'science' },
  { secret: 'Kidney', hint: 'Filter', theme: 'science' },
  { secret: 'Skeleton', hint: 'Bones', theme: 'science' },
  { secret: 'Muscle', hint: 'Movement', theme: 'science' },
  { secret: 'Photosynthesis', hint: 'Sunlight', theme: 'science' },
  { secret: 'Respiration', hint: 'Oxygen', theme: 'science' },
  { secret: 'Ecosystem', hint: 'Nature', theme: 'science' },
  { secret: 'Fossil Fuel', hint: 'Energy', theme: 'science' },
  { secret: 'Volcano', hint: 'Lava', theme: 'science' },

   // League of Legends
  { secret: 'Aatrox', hint: 'Shurima', theme: 'league' },
  { secret: 'Ahri', hint: 'Ionia', theme: 'league' },
  { secret: 'Akali', hint: 'Ionia', theme: 'league' },
  { secret: 'Alistar', hint: 'Demacia', theme: 'league' },
  { secret: 'Amumu', hint: 'Shurima', theme: 'league' },
  { secret: 'Anivia', hint: 'Freljord', theme: 'league' },
  { secret: 'Annie', hint: 'Noxus', theme: 'league' },
  { secret: 'Aphelios', hint: 'Targon', theme: 'league' },
  { secret: 'Ashe', hint: 'Freljord', theme: 'league' },
  { secret: 'Aurelion Sol', hint: 'Targon', theme: 'league' },
  { secret: 'Azir', hint: 'Shurima', theme: 'league' },
  { secret: 'Bard', hint: 'Ionia', theme: 'league' },
  { secret: 'Blitzcrank', hint: 'Zaun', theme: 'league' },
  { secret: 'Brand', hint: 'Freljord', theme: 'league' },
  { secret: 'Braum', hint: 'Freljord', theme: 'league' },
  { secret: 'Caitlyn', hint: 'Piltover', theme: 'league' },
  { secret: 'Camille', hint: 'Piltover', theme: 'league' },
  { secret: 'Cassiopeia', hint: 'Shurima', theme: 'league' },
  { secret: 'Cho\'Gath', hint: 'Void', theme: 'league' },
  { secret: 'Corki', hint: 'Piltover', theme: 'league' },
  { secret: 'Darius', hint: 'Noxus', theme: 'league' },
  { secret: 'Diana', hint: 'Targon', theme: 'league' },
  { secret: 'Dr. Mundo', hint: 'Zaun', theme: 'league' },
  { secret: 'Draven', hint: 'Noxus', theme: 'league' },
  { secret: 'Ekko', hint: 'Zaun', theme: 'league' },
  { secret: 'Elise', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Evelynn', hint: 'Ixtal', theme: 'league' },
  { secret: 'Ezreal', hint: 'Piltover', theme: 'league' },
  { secret: 'Fiddlesticks', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Fiora', hint: 'Demacia', theme: 'league' },
  { secret: 'Fizz', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Galio', hint: 'Demacia', theme: 'league' },
  { secret: 'Gangplank', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Garen', hint: 'Demacia', theme: 'league' },
  { secret: 'Gnar', hint: 'Freljord', theme: 'league' },
  { secret: 'Gragas', hint: 'Freljord', theme: 'league' },
  { secret: 'Graves', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Gwen', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Hecarim', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Heimerdinger', hint: 'Piltover', theme: 'league' },
  { secret: 'Illaoi', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Irelia', hint: 'Ionia', theme: 'league' },
  { secret: 'Ivern', hint: 'Ionia', theme: 'league' },
  { secret: 'Janna', hint: 'Ionia', theme: 'league' },
  { secret: 'Jarvan IV', hint: 'Demacia', theme: 'league' },
  { secret: 'Jhin', hint: 'Ionia', theme: 'league' },
  { secret: 'Jinx', hint: 'Zaun', theme: 'league' },
  { secret: 'Kai\'Sa', hint: 'Void', theme: 'league' },
  { secret: 'Karma', hint: 'Ionia', theme: 'league' },
  { secret: 'Karthus', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Kassadin', hint: 'Shurima', theme: 'league' },
  { secret: 'Katarina', hint: 'Noxus', theme: 'league' },
  { secret: 'Kayle', hint: 'Demacia', theme: 'league' },
  { secret: 'Kennen', hint: 'Ionia', theme: 'league' },
  { secret: 'Kha\'Zix', hint: 'Void', theme: 'league' },
  { secret: 'Kindred', hint: 'Ionia', theme: 'league' },
  { secret: 'Kled', hint: 'Noxus', theme: 'league' },
  { secret: 'Kog\'Maw', hint: 'Void', theme: 'league' },
  { secret: 'LeBlanc', hint: 'Noxus', theme: 'league' },
  { secret: 'Lee Sin', hint: 'Ionia', theme: 'league' },
  { secret: 'Leona', hint: 'Targon', theme: 'league' },
  { secret: 'Lillia', hint: 'Ionia', theme: 'league' },
  { secret: 'Lissandra', hint: 'Freljord', theme: 'league' },
  { secret: 'Lucian', hint: 'Demacia', theme: 'league' },
  { secret: 'Lulu', hint: 'Bandle City', theme: 'league' },
  { secret: 'Lux', hint: 'Demacia', theme: 'league' },
  { secret: 'Malphite', hint: 'Shurima', theme: 'league' },
  { secret: 'Miss Fortune', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Mordekaiser', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Morgana', hint: 'Demacia', theme: 'league' },
  { secret: 'Nami', hint: 'Piltover', theme: 'league' },
  { secret: 'Nasus', hint: 'Shurima', theme: 'league' },
  { secret: 'Nautilus', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Neeko', hint: 'Ixtal', theme: 'league' },
  { secret: 'Nidalee', hint: 'Shurima', theme: 'league' },
  { secret: 'Nocturne', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Nunu & Willump', hint: 'Freljord', theme: 'league' },
  { secret: 'Olaf', hint: 'Freljord', theme: 'league' },
  { secret: 'Orianna', hint: 'Piltover', theme: 'league' },
  { secret: 'Ornn', hint: 'Freljord', theme: 'league' },
  { secret: 'Pantheon', hint: 'Targon', theme: 'league' },
  { secret: 'Poppy', hint: 'Demacia', theme: 'league' },
  { secret: 'Pyke', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Qiyana', hint: 'Ixtal', theme: 'league' },
  { secret: 'Quinn', hint: 'Demacia', theme: 'league' },
  { secret: 'Rakan', hint: 'Ionia', theme: 'league' },
  { secret: 'Rammus', hint: 'Shurima', theme: 'league' },
  { secret: 'Rek\'Sai', hint: 'Void', theme: 'league' },
  { secret: 'Rell', hint: 'Noxus', theme: 'league' },
  { secret: 'Renata Glasc', hint: 'Zaun', theme: 'league' },
  { secret: 'Renekton', hint: 'Shurima', theme: 'league' },
  { secret: 'Riven', hint: 'Ionia', theme: 'league' },
  { secret: 'Rumble', hint: 'Zaun', theme: 'league' },
  { secret: 'Ryze', hint: 'Freljord', theme: 'league' },
  { secret: 'Samira', hint: 'Noxus', theme: 'league' },
  { secret: 'Sejuani', hint: 'Freljord', theme: 'league' },
  { secret: 'Senna', hint: 'Demacia', theme: 'league' },
  { secret: 'Seraphine', hint: 'Piltover', theme: 'league' },
  { secret: 'Sett', hint: 'Ionia', theme: 'league' },
  { secret: 'Shaco', hint: 'Shurima', theme: 'league' },
  { secret: 'Shen', hint: 'Ionia', theme: 'league' },
  { secret: 'Shyvana', hint: 'Demacia', theme: 'league' },
  { secret: 'Singed', hint: 'Zaun', theme: 'league' },
  { secret: 'Sion', hint: 'Noxus', theme: 'league' },
  { secret: 'Sivir', hint: 'Shurima', theme: 'league' },
  { secret: 'Skarner', hint: 'Shurima', theme: 'league' },
  { secret: 'Sona', hint: 'Demacia', theme: 'league' },
  { secret: 'Soraka', hint: 'Targon', theme: 'league' },
  { secret: 'Swain', hint: 'Noxus', theme: 'league' },
  { secret: 'Sylas', hint: 'Demacia', theme: 'league' },
  { secret: 'Syndra', hint: 'Ionia', theme: 'league' },
  { secret: 'Tahm Kench', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Taliyah', hint: 'Shurima', theme: 'league' },
  { secret: 'Talon', hint: 'Noxus', theme: 'league' },
  { secret: 'Taric', hint: 'Targon', theme: 'league' },
  { secret: 'Teemo', hint: 'Bandle City', theme: 'league' },
  { secret: 'Thresh', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Tristana', hint: 'Bandle City', theme: 'league' },
  { secret: 'Trundle', hint: 'Freljord', theme: 'league' },
  { secret: 'Tryndamere', hint: 'Freljord', theme: 'league' },
  { secret: 'Twisted Fate', hint: 'Bilgewater', theme: 'league' },
  { secret: 'Twitch', hint: 'Zaun', theme: 'league' },
  { secret: 'Udyr', hint: 'Freljord', theme: 'league' },
  { secret: 'Urgot', hint: 'Zaun', theme: 'league' },
  { secret: 'Varus', hint: 'Ionia', theme: 'league' },
  { secret: 'Vayne', hint: 'Demacia', theme: 'league' },
  { secret: 'Veigar', hint: 'Bandle City', theme: 'league' },
  { secret: 'Vel\'Koz', hint: 'Void', theme: 'league' },
  { secret: 'Vi', hint: 'Piltover', theme: 'league' },
  { secret: 'Viego', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Viktor', hint: 'Zaun', theme: 'league' },
  { secret: 'Vladimir', hint: 'Noxus', theme: 'league' },
  { secret: 'Volibear', hint: 'Freljord', theme: 'league' },
  { secret: 'Warwick', hint: 'Zaun', theme: 'league' },
  { secret: 'Wukong', hint: 'Ionia', theme: 'league' },
  { secret: 'Xayah', hint: 'Ionia', theme: 'league' },
  { secret: 'Xerath', hint: 'Shurima', theme: 'league' },
  { secret: 'Xin Zhao', hint: 'Demacia', theme: 'league' },
  { secret: 'Yasuo', hint: 'Ionia', theme: 'league' },
  { secret: 'Yone', hint: 'Ionia', theme: 'league' },
  { secret: 'Yorick', hint: 'Shadow Isles', theme: 'league' },
  { secret: 'Yuumi', hint: 'Bandle City', theme: 'league' },
  { secret: 'Zac', hint: 'Zaun', theme: 'league' },
  { secret: 'Zed', hint: 'Ionia', theme: 'league' },
  { secret: 'Ziggs', hint: 'Zaun', theme: 'league' },
  { secret: 'Zilean', hint: 'Shurima', theme: 'league' },
  { secret: 'Zoe', hint: 'Targon', theme: 'league' },
  { secret: 'Zyra', hint: 'Ionia', theme: 'league' },
];
